version: '3.9'

services:
  mssql:
    hostname: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      - SA_PASSWORD=@Passw0rd
      - ACCEPT_EULA=Y
    volumes:
      - mssql-data:/var/lib/mssql/data
    ports:
      - 1433:1433
    networks:
      - app

  webapi:
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      - ConnectionStrings__WebApiDatabase=$CONNECTION_STRING
    ports:
      - 5001:80
    depends_on:
      - mssql
    networks:
      - app

 # busybox:
 #   image: ubuntu
 #   stdin_open: true      # docker run -i
 #   tty: true             # docker run -t
 #   networks:
 #     - app

networks:
  app:
    driver: bridge

volumes:
  mssql-data: