version: '3.9'

services:
  mssql:
    hostname: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      - SA_PASSWORD=@Passw0rd
      - ACCEPT_EULA=Y
    volumes:
      - mssql-data:/var/lib/mssql/data
    ports:
      - 1433:1433
    networks:
      - app

  webapi:
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      - ConnectionStrings__WebApiDatabase=Data Source=mssql; Initial Catalog=dotnet-5-crud-api; User Id=sa; Password=@Passw0rd
    ports:
      - 5001:80
    depends_on:
      - mssql
    networks:
      - app

 #webapi2:
 #  build:
 #    context: .
 #    dockerfile: ./dockerfile
 #  environment:
 #    - ConnectionStrings__WebApiDatabase=$CONNECTION_STRING
 #  ports:
 #    - 5001:80
 #  depends_on:
 #    - mssql
 #  networks:
 #    - app

 #efmigration:
 #  image: mcr.microsoft.com/dotnet/sdk:5.0-focal
 #  stdin_open: true      # docker exec -it 
 #  tty: true            
 #  networks:
 #    - app
 #  volumes:
 #    - .:/mnt/work

networks:
  app:
    driver: bridge

volumes:
  mssql-data: